name: "build-test"
on: # rebuild any PRs and any branch changes
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14"]
    if: github.repository == 'CaoMeiYouRen/push-all-in-one-action'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js@${{ matrix.node }} environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package.json') }}
      - run: yarn
      - run: npm run lint
      - run: npm run build
