name: "Test"
on: # rebuild any PRs and any branch changes
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.repository == 'CaoMeiYouRen/push-all-in-one-action'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js@lts environment
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package.json') }}
      - run: yarn
      - run: yarn run lint
      - run: yarn run build
